### ISSUE TITLE
Missing optional dependencies break JEI Runtime

### ISSUE THREAD

**Issue by laceflowermc** [ModernGamingWorlds-Mods/Wooden-Utilities#14]
**Versions**

Minecraft: 1.16.5
Forge: 36.1.35
Wooden Utilities: 1.0.6
JEI: 7.7.1.111

**Describe the bug**
JEI runs into an error when attempting to load recipes from optional dependencies missing in the running instance, failing to interpret the missing inputs/outputs.

**How to reproduce**
1. Load a world with JEI and Wooden Utilities in the same instance
2. Check latest.log
3. In some cases, this may cause the Crafting tab to disappear entirely

**Expected behavior**
The recipes from missing dependencies should never be loaded into the RecipeManager (which i thiiiiink JEI pulls from for its recipes)

Attached latest.log that describes the problem better than i can:
https://paste.ubuntu.com/p/PDYx4VTCNm/

**Comment by ModernGamingWorld** [comment]
@laceflowermc The mods being rewritten so if there are major issues with the current versions on curseforge, we have no eta on when a fix will be out
