### ISSUE TITLE
Client crash when using a Woodcutter without an Axe inserted

### ISSUE THREAD

**Issue by laceflowermc** [ModernGamingWorlds-Mods/Wooden-Utilities#15]
**Versions**

Minecraft: 1.16.5
Forge: 36.1.whatever i dont wanna check
Wooden Utilities: 1.0.6
Modpack: Create From Scratch / Create From Scratch 2

**Describe the bug**
The client crashes when attempting to use the Woodcutter without inserting an axe.

**How to reproduce**
1. Put wood in woodcutter, and only wood.
2. Attempt to use a woodcutter recipe.
3. CTD!

**Expected behavior**
not crashing to desktop

**Crash Pastes**
https://paste.ee/p/jKBdQ
https://paste.ubuntu.com/p/TYCKWDhZ6G/

**Comment by ModernGamingWorld** [comment]
@laceflowermc The mods being rewritten so if there are major issues with the current versions on curseforge, we have no eta on when a fix will be out

Check the Project Page and you will see alot is being redone
